version: '3'
services:
    mps-host-php-fpm:
        container_name: MeetingMpsPhpFpm
        build:
            args:
                user: devuser01
                uid: 1000
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        working_dir: /backend
        volumes:
            - './laravel:/backend' # Laravel app
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        networks:
            - nando_webnet

    mps-host-api:
        container_name: MeetingMpsHostApi
        image: 'nginx:alpine'
        depends_on:
            - mps-host-php-fpm
        working_dir: /laravel
        volumes:
            - './laravel:/backend'
            - './docker/nginx/nginx-api.conf:/etc/nginx/conf.d/default.conf'
        labels:
            - "traefik.http.routers.mps-host-api.rule=Host(`meeting-api.mpsrecuperi.it`)"
            - "traefik.http.routers.mps-host-api.entrypoints=websecure"
            - "traefik.http.routers.mps-host-api.tls.certresolver=myresolver"
        networks:
            - nando_webnet

    mps-host-front:
        container_name: MeetingMpsVueFrontDev
        image: 'nginx:alpine'
        working_dir: /front
        volumes:
            - ./front:/front
            - './docker/nginx/nginx-front.conf:/etc/nginx/conf.d/default.conf'
        labels:
            - "traefik.http.routers.mps-host-front.rule=Host(`meeting.mpsrecuperi.it`)"
            - "traefik.http.routers.mps-host-front.entrypoints=websecure"
            - "traefik.http.routers.mps-host-front.tls.certresolver=myresolver"
            - traefik.http.routers.mps-host-front.middlewares=mps-host-front-auth
            - traefik.http.middlewares.mps-host-front-auth.basicauth.users=M33T1NG:$$2y$$05$$2MGmReyPa3VVpaCptqc1kOnvoVB2OkaMaWUzO3QPwciGEs9p.QYFO
            - traefik.http.middlewares.mps-host-front-auth.basicauth.realm=Accedi per ottenere i super poteri ;)
        networks:
            - nando_webnet

    mps-host-db:
        image: mysql:8.0
        container_name: MeetingMpsDatabase
        environment:
            MYSQL_DATABASE: "meeting-mps-d3v3l0p3r"
            MYSQL_USER: "meeting-mps-d3v3l0p3r"
            MYSQL_ROOT: "root"
            MYSQL_PASSWORD: "d3v3l0p3r"
            MYSQL_ROOT_PASSWORD: "d3v3l0p3r"
        volumes:
            - './dbData:/var/lib/mysql'
        ports:
            - "3310:3306"
        networks:
            - nando_webnet

    mps-host-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: MeetingMpsHostPhpMyAdmin
        links:
            - mps-host-db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        labels:
            - "traefik.http.routers.mps-host-phpmyadmin.rule=Host(`meeting-db.mpsrecuperi.it`)"
            - "traefik.http.routers.mps-host-phpmyadmin.entrypoints=websecure"
            - "traefik.http.routers.mps-host-phpmyadmin.tls.certresolver=myresolver"
        networks:
            - nando_webnet

networks:
    nando_webnet:
        external: true